config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path:       '',
             path_names: {
               sign_in:      'login',
               sign_out:     'logout',
               password:     'secret',
               confirmation: 'verification',
               unlock:       'unblock',
               registration: 'register',
               sign_up:      'cmon-let-me-in',
             }
  resources :posts, param: :slug
  root 'static#index'
  get 'about', to: 'static#about'
  get 'help', to: 'static#help'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, length: { minimum: 5 }
  validates :slug, uniqueness: true
  before_create :set_slug

  def update_visit_count
    update(visit_count: visit_count + 1)
  end

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = "#{title.parameterize}-#{SecureRandom.hex(4)}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at DESC').page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.update_visit_count if @post.present?
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by slug: params[:slug]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index; end

  def about; end

  def help; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %title CiConceptual
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navigation'
    %br
    .container
      = render partial: 'shared/flash', flash: flash
      = yield
    = render 'shared/footer'

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  = render 'shared/errors', object: post
  .form-group
    = form.label :title
    = form.text_field :title, class: "form-control", placeholder: "Title"
  .form-group
    = form.trix_editor :body, as: :trix_editor
  .actions
    = form.submit "Send", class: "btn btn-block btn-outline-dark"

:javascript 
  $('trix-editor').css("min-height", "200px");

app/views/posts/_posts.html.haml
- @posts.each do |post|
  %tr{id: "log-#{post.id}"}
    %td.text-center= post.title
    %td.text-center= sanitize(sanitize(post.body, tags: ['h1']).truncate(50))
    %td.text-center= post.visit_count
    %td.text-center
      = link_to(post_path(post)) do
        = material_icon.link
      = link_to(edit_post_path(post), class: 'text-muted') do
        = material_icon.edit
      = link_to(post_path(post), :data => { :confirm => "Are you sure?" }, :method => :delete, class: 'text-danger') do
        = material_icon.delete

app/views/posts/edit.html.haml
%h1 Editing Post
.container.container-content
  = render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.d-flex.flex-row.align-items-center
  %h1{ class: 'flex-grow-1'} All Posts
  = link_to('New Post', new_post_path, class: 'btn btn-dark btn-sm')
.container.container-content
  %table.table.table-borderless.table-responsive-sm.table-hover
    %thead
      %th.text-center 
        %h6 Title
      %th.text-center
        %h6 Body
      %th.text-center 
        %h6 Visit Count
      %th.text-center 
        %h6 Actions
    %tbody#posts_container
      = render 'posts'
%br
#posts_paginator.row.justify-content-center.align-items-center
  = paginate @posts, remote: true

app/views/posts/index.js.erb
$('#posts_container').html('<%= escape_javascript(raw(render 'posts')) %>');
$('#posts_paginator').html('<%= escape_javascript(paginate(@posts, remote: true)) %>');

app/views/posts/new.html.haml
.d-flex.flex-row.align-items-center
  %h1 New Post
.container.container-content
  = render 'form', post: @post

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @post.title
%p
  %strong Body:
  = raw @post.body
%p
  %strong Visit count:
  = @post.visit_count

app/views/shared/_errors.html.haml
- if object.errors.any?
  #error_explanation.alert.alert-danger.alert-dismissible.fade.show{role: "alert"}
    %h4
      = pluralize(object.errors.count, "error")
      prohibited
      this object from being saved:
    %ul.list-unstyled
      - object.errors.full_messages.each do |msg|
        %li= msg
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×

app/views/shared/_flash.html.haml
- flash.each do |type, msg|
  %div{:class => "alert #{bootstrap_class_for_flash(type)} alert-dismissable fade show"}
    = msg
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %span.text-muted 2018 All rights reserved

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "CI", root_path, class: "navbar-brand"
  %button.navbar-toggler.p-0.border-0{"aria-controls" => "navbarToggleExternalContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarToggleExternalContent", "data-toggle" => "offcanvas", type: "button"}
    %span.navbar-toggler-icon
  #navbarToggleExternalContent.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item
          = link_to 'Posts' , posts_path, class: "nav-link"
      %li.nav-item
        = link_to 'About' , about_path, class: "nav-link"
      %li.nav-item
        = link_to 'Help' , help_path, class: "nav-link"
    %ul.navbar-nav.ml-auto
      - if user_signed_in?
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown.d-flex.align-items-center{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
            Actions
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to 'New Post', new_post_path, class: "dropdown-item"
            = link_to 'All Posts', posts_path, class: "dropdown-item"
            .dropdown-divider
            = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
      - else
        %li.nav-item
          = link_to "Login", new_user_session_path, class: 'nav-link'